import js from "@eslint/js";
import tseslint from "typescript-eslint";
import security from "eslint-plugin-security";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";

/**
 * Flat ESLint config for this Next.js (App Router) + TypeScript app.
 *
 * Layers: JS recommended → typescript-eslint recommended →
 * eslint-plugin-security recommended → Next.js core-web-vitals. As of
 * eslint-config-next 16 the Next config ships as a NATIVE flat-config array, so
 * it is spread in directly (no FlatCompat / eslintrc shim). The CI gate runs
 * with `--max-warnings 0`, so anything here must be an error we mean to block on
 * or be turned off — we never leave rules at "warn".
 */
export default tseslint.config(
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      "src/db-types.ts", // committed, auto-generated by pg-to-ts — not hand-linted
      "eslint.config.mjs",
      "public/trace-viewer/**", // vendored Playwright trace viewer (third-party bundle)
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  security.configs.recommended,
  ...nextCoreWebVitals,

  {
    // Flag stale inline disable directives as errors so dead carve-outs can't
    // accumulate — a disable for a rule that no longer fires is pure noise, and
    // `--max-warnings 0` makes it a hard block. (Re-enabled from a legacy
    // carve-out; the stale `no-console` directives it surfaced were removed.)
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    rules: {
      // ── Kept OFF by documented design (NOT a TODO) ────────────────────────
      // Noisy, high false-positive rule: flags every computed member access
      // (e.g. TONE_VAR[token], lookup tables keyed by validated unions). Every
      // one of the ~71 current hits is an internal, constant-keyed lookup — none
      // are user-controlled, so none are defects. Re-enabling would mean ~71
      // inline disables for zero safety gain, so this stays OFF as a deliberate
      // decision. Revisit ONLY if a real injection pattern (a user-controlled
      // key reaching a sink) actually emerges.
      "security/detect-object-injection": "off",

      // eslint-plugin-react-hooks (via eslint-config-next 16). Fires on the
      // "default-expand the latest run once" effect in src/app/checks/[id]/page.tsx.
      // Each hit is a real effect→state anti-pattern needing case-by-case
      // judgment, not a mechanical fix, so it is handled in its OWN follow-up PR
      // rather than bundled with the mechanical cleanup. Left OFF here on purpose.
      // TODO(eslint-hooks PR): re-enable and derive the initial expanded run at
      // render time (expandedRun ?? recent_runs[0]?.id) instead of in an effect.
      "react-hooks/set-state-in-effect": "off",
    },
  },

  {
    // The contract checks + capture script read/write FIXED local fixture paths (contract/real/*.json),
    // never user input — the non-literal-fs-filename security rule is a pure false positive here.
    files: ["contract/**"],
    rules: {
      "security/detect-non-literal-fs-filename": "off",
    },
  },

  {
    // CI static-parse tooling (check-*-coverage): reads REPO files by computed path and builds regexes from
    // our OWN manifest (table/column/union names), never user input — both `security/detect-non-literal-*`
    // rules are pure false positives here, same carve-out as contract/** above.
    files: ["scripts/**"],
    rules: {
      "security/detect-non-literal-fs-filename": "off",
      "security/detect-non-literal-regexp": "off",
    },
  },
);
