import path from "node:path";
import { fileURLToPath } from "node:url";

import js from "@eslint/js";
import tseslint from "typescript-eslint";
import security from "eslint-plugin-security";
import { FlatCompat } from "@eslint/eslintrc";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory: __dirname });

/**
 * Flat ESLint config for this Next.js (App Router) + TypeScript app.
 *
 * Layers: JS recommended → typescript-eslint recommended →
 * eslint-plugin-security recommended → Next.js core-web-vitals (via FlatCompat,
 * since eslint-config-next is still eslintrc-shaped). The CI gate runs with
 * `--max-warnings 0`, so anything here must be an error we mean to block on or
 * be turned off — we never leave rules at "warn".
 */
export default tseslint.config(
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      "src/db-types.ts", // committed, auto-generated by pg-to-ts — not hand-linted
      "eslint.config.mjs",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  security.configs.recommended,
  ...compat.extends("next/core-web-vitals"),

  {
    // `--max-warnings 0` is the gate, so a stale inline disable directive would
    // fail CI. One such directive remains in MVP app code; reporting is turned
    // off here as a legacy carve-out.
    // TODO(eslint-findings PR): re-enable, then remove the stale
    // `eslint-disable-next-line` in src/app/checks/[id]/page.tsx.
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
    rules: {
      // ── Legacy / baseline carve-outs ──────────────────────────────────────
      // These rules fire on existing MVP code. Per the security-stack rollout
      // they are turned OFF here (never downgraded to "warn") so the gate is
      // green for new code; re-enabling each and fixing the findings is a
      // SEPARATE follow-up PR. Each carries a TODO so the debt stays visible.

      // Noisy, high false-positive rule: flags every computed member access
      // (e.g. TONE_VAR[token], lookup tables keyed by validated unions). All
      // current sinks are internal constant-keyed lookups, not user input.
      // Kept OFF intentionally rather than annotating each safe access.
      "security/detect-object-injection": "off",

      // Deliberate <img> usage: failure-artifact screenshots come from
      // arbitrary runner/blob hosts, so next/image optimization doesn't apply.
      // TODO(eslint-findings PR): migrate to next/image w/ a custom loader, or
      // confirm this stays off by design.
      "@next/next/no-img-element": "off",

      // One dead import in src/components/app-shell.tsx (statusRank).
      // TODO(eslint-findings PR): re-enable and remove unused symbols.
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
);
