/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@synthwatch-pg-e2.postgres.database.azure.com:5432/synthwatch?sslmode=require -t checks -t runs -t run_steps -t run_metrics -t incidents -s public
 *
 */


export type Json = unknown;

// Table checks
export interface Checks {
  id: number;
  name: string;
  kind: string;
  target_url: string;
  flow_name: string | null;
  method: string;
  expected_status: number;
  body_must_contain: string | null;
  interval_seconds: number;
  last_run_at: Date | null;
  timeout_ms: number;
  failure_threshold: number;
  severity: string;
  enabled: boolean;
  created_at: Date;
  lighthouse_enabled: boolean;
  lighthouse_interval_seconds: number | null;
  lighthouse_form_factor: string;
  perf_budget_lcp_ms: number | null;
  perf_budget_transfer_bytes: number | null;
}
export interface ChecksInput {
  id: number;
  name: string;
  kind: string;
  target_url: string;
  flow_name?: string | null;
  method?: string;
  expected_status?: number;
  body_must_contain?: string | null;
  interval_seconds?: number;
  last_run_at?: Date | null;
  timeout_ms?: number;
  failure_threshold?: number;
  severity?: string;
  enabled?: boolean;
  created_at?: Date;
  lighthouse_enabled?: boolean;
  lighthouse_interval_seconds?: number | null;
  lighthouse_form_factor?: string;
  perf_budget_lcp_ms?: number | null;
  perf_budget_transfer_bytes?: number | null;
}
const checks = {
  tableName: 'checks',
  columns: ['id', 'name', 'kind', 'target_url', 'flow_name', 'method', 'expected_status', 'body_must_contain', 'interval_seconds', 'last_run_at', 'timeout_ms', 'failure_threshold', 'severity', 'enabled', 'created_at', 'lighthouse_enabled', 'lighthouse_interval_seconds', 'lighthouse_form_factor', 'perf_budget_lcp_ms', 'perf_budget_transfer_bytes'],
  requiredForInsert: ['id', 'name', 'kind', 'target_url'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Checks,
  $input: null as unknown as ChecksInput
} as const;

// Table runs
export interface Runs {
  id: number;
  check_id: number;
  status: string;
  started_at: Date;
  finished_at: Date | null;
  duration_ms: number | null;
  http_status: number | null;
  error_message: string | null;
  failed_step: string | null;
  screenshot_url: string | null;
}
export interface RunsInput {
  id: number;
  check_id: number;
  status?: string;
  started_at?: Date;
  finished_at?: Date | null;
  duration_ms?: number | null;
  http_status?: number | null;
  error_message?: string | null;
  failed_step?: string | null;
  screenshot_url?: string | null;
}
const runs = {
  tableName: 'runs',
  columns: ['id', 'check_id', 'status', 'started_at', 'finished_at', 'duration_ms', 'http_status', 'error_message', 'failed_step', 'screenshot_url'],
  requiredForInsert: ['id', 'check_id'],
  primaryKey: 'id',
  foreignKeys: { check_id: { table: 'checks', column: 'id', $type: null as unknown as Checks }, },
  $type: null as unknown as Runs,
  $input: null as unknown as RunsInput
} as const;

// Table run_steps
export interface RunSteps {
  id: number;
  run_id: number;
  step_index: number;
  name: string;
  status: string;
  duration_ms: number;
  error_message: string | null;
  started_at: Date;
}
export interface RunStepsInput {
  id: number;
  run_id: number;
  step_index: number;
  name: string;
  status: string;
  duration_ms: number;
  error_message?: string | null;
  started_at?: Date;
}
const run_steps = {
  tableName: 'run_steps',
  columns: ['id', 'run_id', 'step_index', 'name', 'status', 'duration_ms', 'error_message', 'started_at'],
  requiredForInsert: ['id', 'run_id', 'step_index', 'name', 'status', 'duration_ms'],
  primaryKey: 'id',
  foreignKeys: { run_id: { table: 'runs', column: 'id', $type: null as unknown as Runs }, },
  $type: null as unknown as RunSteps,
  $input: null as unknown as RunStepsInput
} as const;

// Table run_metrics
export interface RunMetrics {
  id: number;
  run_id: number;
  ttfb_ms: number | null;
  dom_content_loaded_ms: number | null;
  load_event_ms: number | null;
  fcp_ms: number | null;
  lcp_ms: number | null;
  transfer_bytes: number | null;
  resource_count: number | null;
  dom_node_count: number | null;
  js_heap_bytes: number | null;
  cpu_time_ms: number | null;
  layout_count: number | null;
  recalc_style_count: number | null;
  captured_at: Date;
}
export interface RunMetricsInput {
  id: number;
  run_id: number;
  ttfb_ms?: number | null;
  dom_content_loaded_ms?: number | null;
  load_event_ms?: number | null;
  fcp_ms?: number | null;
  lcp_ms?: number | null;
  transfer_bytes?: number | null;
  resource_count?: number | null;
  dom_node_count?: number | null;
  js_heap_bytes?: number | null;
  cpu_time_ms?: number | null;
  layout_count?: number | null;
  recalc_style_count?: number | null;
  captured_at?: Date;
}
const run_metrics = {
  tableName: 'run_metrics',
  columns: ['id', 'run_id', 'ttfb_ms', 'dom_content_loaded_ms', 'load_event_ms', 'fcp_ms', 'lcp_ms', 'transfer_bytes', 'resource_count', 'dom_node_count', 'js_heap_bytes', 'cpu_time_ms', 'layout_count', 'recalc_style_count', 'captured_at'],
  requiredForInsert: ['id', 'run_id'],
  primaryKey: 'id',
  foreignKeys: { run_id: { table: 'runs', column: 'id', $type: null as unknown as Runs }, },
  $type: null as unknown as RunMetrics,
  $input: null as unknown as RunMetricsInput
} as const;

// Table incidents
export interface Incidents {
  id: number;
  check_id: number;
  status: string;
  severity: string;
  opened_at: Date;
  resolved_at: Date | null;
  opened_run_id: number | null;
  resolved_run_id: number | null;
  consecutive_failures: number;
  summary: string | null;
}
export interface IncidentsInput {
  id: number;
  check_id: number;
  status: string;
  severity: string;
  opened_at?: Date;
  resolved_at?: Date | null;
  opened_run_id?: number | null;
  resolved_run_id?: number | null;
  consecutive_failures?: number;
  summary?: string | null;
}
const incidents = {
  tableName: 'incidents',
  columns: ['id', 'check_id', 'status', 'severity', 'opened_at', 'resolved_at', 'opened_run_id', 'resolved_run_id', 'consecutive_failures', 'summary'],
  requiredForInsert: ['id', 'check_id', 'status', 'severity'],
  primaryKey: 'id',
  foreignKeys: {
    check_id: { table: 'checks', column: 'id', $type: null as unknown as Checks },
    opened_run_id: { table: 'runs', column: 'id', $type: null as unknown as Runs },
    resolved_run_id: { table: 'runs', column: 'id', $type: null as unknown as Runs },
  },
  $type: null as unknown as Incidents,
  $input: null as unknown as IncidentsInput
} as const;


export interface TableTypes {
  checks: {
    select: Checks;
    input: ChecksInput;
  };
  runs: {
    select: Runs;
    input: RunsInput;
  };
  run_steps: {
    select: RunSteps;
    input: RunStepsInput;
  };
  run_metrics: {
    select: RunMetrics;
    input: RunMetricsInput;
  };
  incidents: {
    select: Incidents;
    input: IncidentsInput;
  };
}

export const tables = {
  checks,
  runs,
  run_steps,
  run_metrics,
  incidents,
}
